apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8soauth2-proxy-controller
  labels:
    control-plane: controller
spec:
  selector:
    matchLabels:
      app: k8soauth2-proxy-controller
  replicas: 1
  template:
    metadata:
      labels:
        app: k8soauth2-proxy-controller
    spec:
      containers:
      - command:
        - /manager
        image: ghcr.io/doodlescheduling/k8soauth2-proxy-controller:latest
        imagePullPolicy: IfNotPresent
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
        name: manager
        ports:
        - containerPort: 9557
          name: healthz
          protocol: TCP
        - containerPort: 9556
          name: metrics
          protocol: TCP
        - containerPort: 8080
          name: http
          protocol: TCP
        readinessProbe:
          httpGet:
            path: /readyz
            port: healthz
        livenessProbe:
          httpGet:
            path: /healthz
            port: healthz
        resources:
          limits:
            cpu: 200m
            memory: 500Mi
          requests:
            cpu: 100m
            memory: 200Mi
      terminationGracePeriodSeconds: 10
