apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namePrefix: k8soauth2-proxy-
resources:
- role.yaml
- role_binding.yaml
- leader_election_role.yaml
- leader_election_role_binding.yaml
